"""Validation against real, non-OCP-generated STEP data — a genuine u-blox
product assembly exported from SolidWorks 2014 (see examples/real_world/NOTICE.md).
Every other fixture in this repo is synthetic, generated by cad-diff's own
writer; this file is the roadmap's actual go/no-go gate: does the pipeline
hold up on real, complex, multi-part, spline-containing industrial geometry?
"""

from pathlib import Path

import pytest

from cad_diff.face_matcher import match_faces
from cad_diff.face_signatures import extract_faces
from cad_diff.matcher import match_solids
from cad_diff.signatures import fingerprint_solid
from cad_diff.step_io import load_step

REAL_WORLD = Path(__file__).parent.parent / "examples" / "real_world"


def test_real_assembly_decomposes_into_named_leaf_solids():
    # Real assemblies come back from XCAF as one compound wrapping multiple
    # parts, not one atomic shape — this is the case load_step's recursive
    # decomposition exists for.
    items = load_step(REAL_WORLD / "SAM_AP203.STEP")
    names = {name for name, shape in items}

    assert names == {"Sam cavity", "SAM PCB", "SAM ANT"}
    for name, shape in items:
        assert shape.ShapeType().name == "TopAbs_SOLID"


def test_ap203_vs_ap214_reexport_has_no_false_positives():
    # Same real assembly, same real geometry, exported 23 seconds apart in
    # two different STEP schemas by the same SolidWorks session. A schema
    # change alone must not register as a geometric change.
    base_items = load_step(REAL_WORLD / "SAM_AP203.STEP")
    mod_items = load_step(REAL_WORLD / "SAM_AP214.STEP")

    base_fps = [fingerprint_solid(n, s) for n, s in base_items]
    mod_fps = [fingerprint_solid(n, s) for n, s in mod_items]
    diffs = match_solids(base_fps, mod_fps)

    assert len(diffs) == 3
    assert all(d.status == "unchanged" for d in diffs)


def test_real_hole_edit_is_isolated_not_a_false_positive_storm():
    base_shape, = (s for _, s in load_step(REAL_WORLD / "sam_cavity_v1.step"))
    mod_shape, = (s for _, s in load_step(REAL_WORLD / "sam_cavity_v2_hole.step"))

    diffs = match_faces(extract_faces(base_shape), extract_faces(mod_shape))
    by_status = {}
    for d in diffs:
        by_status.setdefault(d.status, []).append(d)

    # A tiny local edit on a 54-face real part must stay local: exactly the
    # new hole wall (added) and the two walls it passes through (modified),
    # not a cascade of spurious changes across the rest of the part.
    assert len(by_status.get("added", [])) == 1
    assert len(by_status.get("modified", [])) == 2
    assert len(by_status.get("unchanged", [])) == 52
    assert "removed" not in by_status

    added_face = by_status["added"][0].modified
    assert added_face.surface_type == "Cylinder"
    assert added_face.params["radius"] == pytest.approx(0.3, abs=1e-6)

    for modified_diff in by_status["modified"]:
        # cross-sectional area of a 0.3mm-radius hole through a wall
        assert modified_diff.area_delta == pytest.approx(-0.2827, abs=1e-3)


def test_bspline_surfaces_survive_a_real_edit_without_crashing():
    # SAM ANT has genuine free-form BSplineSurface faces (not just planes and
    # cylinders) — this is the highest-complexity real surface type STEP has,
    # and cad-diff never fabricates a dimensional delta for it.
    base_shape, = (s for _, s in load_step(REAL_WORLD / "sam_ant_v1.step"))
    mod_shape, = (s for _, s in load_step(REAL_WORLD / "sam_ant_v2_hole.step"))

    diffs = match_faces(extract_faces(base_shape), extract_faces(mod_shape))
    bspline_diffs = [d for d in diffs if (d.base or d.modified).surface_type == "BSplineSurface"]

    assert len(bspline_diffs) > 0
    for d in bspline_diffs:
        assert d.status in ("unchanged", "modified")
        assert d.param_deltas == {}  # no fabricated dimensional delta for a free-form surface
